
### get user all

GET http://localhost:6969/users

### get user id

GET http://localhost:6969/users/1

### register

POST http://localhost:6969/users
# save id session
Content-Type: application/json

{
  "username": "Margarita",
  "password": "Plovdiv!123",
  "confirm_password": "Plovdiv!123",
  "first_name": "Margarita",
  "last_name": "Velcheva",
  "email": "sofeto@gmail.com",
  "phone_number": "+359884532481",
  "date_of_birth": "1988-12-11"
}

### login
# save id session

POST http://localhost:6969/auth
Content-Type: application/json

{
  "username": "Margarita",
  "password": "Plovdiv!123"
}

### logout

POST http://localhost:6969/logout

### change password
# user is login / get id - session

PUT http://localhost:6969/user/pass
Content-Type: application/json

{
  "current_password": "@wetok345",
  "new_password": "Haideopa123?",
  "confirm_new_password": "Haideopa123?"
}

### change photo
PUT http://localhost:6969/user/photo
Content-Type: application/json
{
  # todo
}

### edit profile
# user is login / get id - session
# check for not null variable

PUT http://localhost:6969/user
Content-Type: application/json

{
  "first_name": null,
  "last_name": null,
  "email": "vodka@abv.bg",
  "phone_number": null
}

### start session
# test URLs

POST http://localhost:6969/start

###
POST http://localhost:6969/check

###

GET http://localhost:6969/bum

### delete
## delete user

PUT localhost:6969/users/{id}





